### ISSUE TITLE
Add pydocstyle to the pre-commit

### ISSUE THREAD

**Issue by MaxJPRey** [pyansys/pyaedt#2429]
### Description of the feature

In the pre-commit, we could use the `pydocstyle` hook.
This will create warnings where documentation is missing when adding new features.

### Steps for implementing the feature

Here is some code to write in the `.pre-commit-config.yaml`.

```
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
    exclude: "tests/"
```
